name: Deploy Functions to Production

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]
    paths:
      - 'UsersFunction/**'
      - 'AnimalsFunction/**'
      - 'PlugginsRandomFunctionOne/**'

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    outputs:
      users-function: ${{ steps.changes.outputs.users-function }}
      animals-function: ${{ steps.changes.outputs.animals-function }}
      plugins-function: ${{ steps.changes.outputs.plugins-function }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            users-function:
              - 'UsersFunction/**'
            animals-function:
              - 'AnimalsFunction/**'
            plugins-function:
              - 'PlugginsRandomFunctionOne/**'

  deploy-functions:
    needs: detect-changes
    if: github.event.pull_request.merged == true && (needs.detect-changes.outputs.users-function == 'true' || needs.detect-changes.outputs.animals-function == 'true' || needs.detect-changes.outputs.plugins-function == 'true')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function-config: [
          { name: 'UsersFunction', path: 'UsersFunction', changed: '${{ needs.detect-changes.outputs.users-function }}' },
          { name: 'AnimalsFunction', path: 'AnimalsFunction', changed: '${{ needs.detect-changes.outputs.animals-function }}' },
          { name: 'PlugginsRandomFunctionOne', path: 'PlugginsRandomFunctionOne', changed: '${{ needs.detect-changes.outputs.plugins-function }}' }
        ]
    steps:
      - name: Checkout code
        if: matrix.function-config.changed == 'true'
        uses: actions/checkout@v4

      - name: Setup .NET
        if: matrix.function-config.changed == 'true'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Azure Login via OIDC
        if: matrix.function-config.changed == 'true'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build Function App
        if: matrix.function-config.changed == 'true'
        run: |
          cd ${{ matrix.function-config.path }}/${{ matrix.function-config.path }}
          echo "🔨 Building ${{ matrix.function-config.name }} for production..."
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet publish --configuration Release --output ./publish --no-build

      - name: Create deployment package
        if: matrix.function-config.changed == 'true'
        run: |
          cd ${{ matrix.function-config.path }}/${{ matrix.function-config.path }}/publish
          zip -r ../../../${{ matrix.function-config.name }}-production-package.zip .
          echo "📦 Production package created: ${{ matrix.function-config.name }}-production-package.zip"

      - name: Get production environments for this function
        if: matrix.function-config.changed == 'true'
        id: get-environments
        run: |
          # Read configuration and extract production environments that use this function
          environments=$(cat config/clients-sqlserver.json | jq -r --arg func "${{ matrix.function-config.name }}" '
            .clients | to_entries[] | 
            select(.value.environments.main.functions.core[]? == $func or 
                   .value.environments.main.functions.plugins[]? == $func) |
            .key
          ' | jq -R -s -c 'split("\n")[:-1]')
          echo "environments=$environments" >> $GITHUB_OUTPUT
          echo "🎯 Will deploy ${{ matrix.function-config.name }} to production environments: $environments"

      - name: Deploy to production environments
        if: matrix.function-config.changed == 'true'
        run: |
          environments='${{ steps.get-environments.outputs.environments }}'
          
          if [ "$environments" = "[]" ] || [ -z "$environments" ]; then
            echo "⏭️  No production environments found for ${{ matrix.function-config.name }}"
            exit 0
          fi
          
          echo "🚀 Deploying ${{ matrix.function-config.name }} to ALL production environments..."
          echo "📋 This PR contained changes to ${{ matrix.function-config.name }}, deploying to:"
          
          for client in $(echo $environments | jq -r '.[]'); do
            echo "   📦 $client-main"
          done
          
          for client in $(echo $environments | jq -r '.[]'); do
            echo ""
            echo "🚀 Deploying ${{ matrix.function-config.name }} to $client-main..."
            
            # Get function app name for this client
            function_app_name="${{ matrix.function-config.name }}-${client}-main"
            resource_group="rg-witag-${client}-main"
            
            echo "   📦 Function App: $function_app_name"
            echo "   📋 Resource Group: $resource_group"
            
            # Deploy using Azure CLI
            az functionapp deployment source config-zip \
              --resource-group "$resource_group" \
              --name "$function_app_name" \
              --src "${{ matrix.function-config.name }}-production-package.zip" \
              --subscription "${{ env.AZURE_SUBSCRIPTION_ID }}"
            
            if [ $? -eq 0 ]; then
              echo "   ✅ Successfully deployed to $function_app_name"
            else
              echo "   ❌ Failed to deploy to $function_app_name"
              exit 1
            fi
          done

      - name: Verify production deployments
        if: matrix.function-config.changed == 'true'
        run: |
          environments='${{ steps.get-environments.outputs.environments }}'
          
          if [ "$environments" = "[]" ] || [ -z "$environments" ]; then
            echo "⏭️  No production environments to verify"
            exit 0
          fi
          
          echo "🔍 Verifying all production deployments..."
          
          for client in $(echo $environments | jq -r '.[]'); do
            function_app_name="${{ matrix.function-config.name }}-${client}-main"
            resource_group="rg-witag-${client}-main"
            
            echo "🔍 Verifying $function_app_name..."
            
            # Check if function app is running
            status=$(az functionapp show \
              --resource-group "$resource_group" \
              --name "$function_app_name" \
              --query "state" \
              --output tsv \
              --subscription "${{ env.AZURE_SUBSCRIPTION_ID }}")
            
            if [ "$status" = "Running" ]; then
              echo "   ✅ $function_app_name is running successfully"
            else
              echo "   ⚠️  $function_app_name status: $status"
            fi
            
            # Get function app URL for quick check
            hostname=$(az functionapp show \
              --resource-group "$resource_group" \
              --name "$function_app_name" \
              --query "defaultHostName" \
              --output tsv \
              --subscription "${{ env.AZURE_SUBSCRIPTION_ID }}")
            
            echo "   🌐 Function App URL: https://$hostname"
          done

      - name: Deployment Summary
        if: matrix.function-config.changed == 'true'
        run: |
          environments='${{ steps.get-environments.outputs.environments }}'
          
          echo ""
          echo "📊 PRODUCTION DEPLOYMENT SUMMARY"
          echo "================================="
          echo "🔧 Function: ${{ matrix.function-config.name }}"
          echo "📋 PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
          echo "👤 Author: ${{ github.event.pull_request.user.login }}"
          echo ""
          echo "🎯 Deployed to production environments:"
          
          for client in $(echo $environments | jq -r '.[]'); do
            function_app_name="${{ matrix.function-config.name }}-${client}-main"
            echo "   ✅ $function_app_name"
          done
          
          echo ""
          echo "🎉 All production deployments completed successfully!"

  notify-completion:
    needs: [detect-changes, deploy-functions]
    if: always() && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Notify deployment status
        run: |
          if [ "${{ needs.deploy-functions.result }}" = "success" ]; then
            echo "🎉 Production functions deployment completed successfully!"
            echo "📋 PR #${{ github.event.pull_request.number }} changes have been deployed to all production environments"
          elif [ "${{ needs.deploy-functions.result }}" = "failure" ]; then
            echo "❌ Production functions deployment failed!"
            echo "📋 PR #${{ github.event.pull_request.number }} changes could not be deployed"
            exit 1
          elif [ "${{ needs.deploy-functions.result }}" = "skipped" ]; then
            echo "⏭️  No function changes detected in PR #${{ github.event.pull_request.number }}"
          fi 